### PR TITLE
Added CORS headers and OPTIONS handling

### PR DESCRIPTION
**Pull request by RyanHow**
Adds CORS headers and OPTIONS handing to satisfy web browser security requirements for cross domain AJAX calls

### CODE REVIEW

**Comment by RyanHow** [comment]
I wonder if there are use cases for setting of any other http headers also.

**Comment by Connoropolous** [comment]
I think looking forward, app developers are likely to want plenty more
control over this area, yes. What has been implemented so far around this
is very minimim viable product type thing. To create new options for the
cli would mean going into '/cmd/hcdev' code, if you're interested.

**Comment by RyanHow** [comment]
Perhaps wait for a few use cases and they can be aggregated under a web server feature enhancement. I don't really want to "pollute" the command line options. Or would it go in the config.json ?

**Comment by Connoropolous** [comment]
Yeah, and for now when using frameworks like react and angular there's
pretty easy proxying from your other port to the web server which takes
care cross origin for now

**Comment by RyanHow** [comment]
Yes. There are viable alternatives at the moment that aren't too difficult.

**Pull request closed without merging**
