### PR TITLE
643 add index for dump, closes #643

### LINKED ISSUE #643: Add an Index to the Dump function
I'd like to be able to set an index when doing 
```
  hcadmin dump clutter --chain --index=4
```
so that I can just get the latest entries for the dump function.

### PR DESCRIPTION
**Pull request by zippy**

### CODE REVIEW

**Comment by zippy** [comment]
Hey @thedavidmeister at one point @philipbeadle asked for dumping from a given start index.  I added that a while back in this branch, but it never got merged.  So I just re-merged from develop into this branch.  I think in the mean time you added some stuff re DOT and also more flags for how to specify the format.  Please give this branch a looksee, and when you are comfortable with it, go-ahead and to the merge back into develop!

**Comment by thedavidmeister** [comment]
@zippy i didn't add any flags for formats, you're thinking of someone else...

FYI though, looks like you accidentally pulled https://github.com/holochain/holochain-proto/pull/645 into this branch as well, which is still a WIP branch

**Comment by zippy** [comment]
right sorry that was Clarence.

**Comment by zippy** [comment]
@philipbeadle bump on this one.  I feel like there are some bugs in this branch, doesn't seem to be working right for me, like the defaults don't match what's happening.  Can you check in with Clarence about this?  Also, what's his github account so I can add him into the contributors team...

**Comment by philipbeadle** [comment]
Clarence is https://github.com/clarenceb. I'll ask him to check this branch.

**Comment by zippy** [comment]
tx. can't request a review until he accepts invitation...

**Comment by clarenceb** [comment]
@zippy the changes mostly look good and work but there are some issues that need to be fixed:

* `hcdev` default chain dump (as string) does not respect the `--index` input (`hcadmin` does, however)
* `Dot()` function in `chain.go` needs to be updated to take `start` parameter for the index offset like in the string `Dump(start int)` function

Other issues not specifically related to your changes and should be fixed elsewhere:

* `--format <string|json|dot>` option is missing from `hcadmin` (I added it to `hcdev` only) -- I recommend raising an issue for this so I can fix it.
* `docker-compose,yml` in the `clutter` repo needs updating to remove the `-no-nat-upnp` flag and change `-port=XXXX` to `-DHTport=XXXX` -- recommend raising an issue in the `clutter` repo

**Pull request merged**
