### PR TITLE
improve comments on code generated with `hcdev init`

### LINKED ISSUE #666: hcdev init command should spit out documented code with clearer intent
sampleZome could be better documented, could be more DRY to highlight intent of fns better

### PR DESCRIPTION
**Pull request by zippy**
closes #666
other tiny cleanup bits too.

### CODE REVIEW

**Comment by Connoropolous** [comment]
@zippy there are however, some tests failing... you are testing locally? is this just a travis based issue?

**Comment by zippy** [comment]
I think it's all timing crap.  I wish I could fix it as locally tests run
just fine...

**Comment by zippy** [comment]
Ok turns out that this is due to a not so smart dependency:  hcdev_test, in testing -cloneExample functionality actually runs that clone against HoloWorld and was looking for the HoloWorld.js file in the HoloWorld zome folder.  It looks like that recently got changed in HoloWorld.  So instead I've made a commit that looks for dna.json which I think is less likely to be changed.  I know this isn't best dependency to have in the tests, but hey, I wanted to test that it actually downloads the repo...

**Comment by thedavidmeister** [comment]
i'll have a play with this some more today

**Pull request merged**
